### ISSUE TITLE
results for Bayesian parameter esti- mation with FME. 

### ISSUE THREAD

**Issue by ling9802** [MPIBGC-TEE/SoilR-exp#3]
I'm sorry I couldn't find a detailed description of Bayesian estimation in the tutorial (Parameter Estimation of Compartment Models in SoilR Using Classical and Bayesian Optimization). How should I go about achieving it ?

**Comment by crlsierra** [comment]
You can find detailed descriptions for Bayesian optimization (Markov chain Monte Carlo) in the documentation of the R package [FME](https://fme.r-forge.r-project.org/), particularly the vignette *Inverse Modelling, Sensitivity and Monte Carlo Analysis in R Using Package FME*, which is included in the FME packge. In general, you would use SoilR to produce a function that returns a desired soil carbon output as a function of some parameters, similarly as how it is described in this [tutorial](https://www.bgc-jena.mpg.de/TEE/optimization/2015/12/09/Fractions-Incubations/), but instead of using the function `modFit`, you would use `modMCMC` for Bayesian optimization.

**Comment by ling9802** [comment]
Thank you for your answer. I have one more question and I changed the model in this section to TwopParallelModel (Identify kinetic SOM fractions with incubation data). There was an error in the code. The detailed changed and error as follow:
![Snipaste_2022-12-06_16-06-56](https://user-images.githubusercontent.com/72969353/205855335-3637d7d8-35e6-4560-b1b9-5bc2021c7372.png)
![image](https://user-images.githubusercontent.com/72969353/205855406-04a88e9d-fbb6-4941-9a2a-565355a18a1f.png)

**Comment by crlsierra** [comment]
The required argument `gam` is missing from your call to the `TwopParallelModel()` function. 
Please read the [documentation of the function](https://mpibgc-tee.github.io/SoilR-exp/TwopParallelModel.html) before posting further questions.
